---
- hosts: localhost
  tasks:
    - name: install cmd apps Linux
      apt:
        name: [
          git,
          terminator,
        ]
        cache_updates: yes
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: nvm load
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh
        dest: /tmp/nvm-install.sh
      when: ansible_facts['os_family'] == "Debian"

    - name: nvm install
      shell: bash nvm-install.sh
      args:
        chdir: /tmp
        creates: ~/.nvm
      when: ansible_facts['os_family'] == "Debian"

    - name: install heroku
      become: true
      snap:
        name: heroku
        classic: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: install cmd apps OSX
      homebrew:
        name: "{{ item }}" 
        state: latest
      loop:
        - "git"
        - "ansible"
        - "htop"
        - "asciinema"
        - "nvm"
        - "tree"
        - "yarn"
        - "terraform"
        - "wget"
        - "heroku/brew/heroku"
        - "pstree"
        - "nmap"
        - "docker"
        - "docker-machine"
        - "cmatrix"
      tags: cmd
      when: ansible_facts['os_family'] == "Darwin"
