- hosts: localhost
  tasks:
    - name: install desktop apps
      homebrew_cask:
        name: "{{ item }}"
        state: latest
      loop: [
        # "google-chrome",
        # "firefox",
        # "1password",
        "skype",
        "telegram",
        "slack",
        "iterm2",
        "docker",
        "google-cloud-sdk",
      ]
      tags: desktop
