---
- hosts: localhost
  tasks:
    - name: copy gitconfig
      copy:
        src: files/.gitconfig
        dest: ~/.gitconfig

    - name: link gitignore
      file:
        src: "{{playbook_dir}}/files/.gitignore"
        dest: ~/.gitignore
        state: link

    - name: copy hgrc
      copy:
        src: files/.hgrc
        dest: ~/.hgrc

    - name: copy ctags
      copy:
        src: files/ctags
        dest: ~/.ctags

    - name: copy eslintignore
      copy:
        src: files/.eslintignore
        dest: ~/.eslintignore

    - name: "link lein profiles"
      file:
        src:  "{{playbook_dir}}/files/profiles.clj" 
        dest: ~/.lein/profiles.clj
        state: link

