---
- hosts: localhost
  tasks:
    - name: "link .spacemacs"
      file:
        src: files/.spacemacs
        dest: ~/.spacemacs
        state: link
    - name: clone spacemacs
      git:
        repo: https://github.com/syl20bnr/spacemacs
        dest: ~/.emacs.d
