---
- hosts: localhost
  tasks:
    - name: copy spacemacs config
      copy:
        src: files/.spacemacs
        dest: ~/.spacemacs
    - name: clone spacemacs
      git:
        repo: https://github.com/syl20bnr/spacemacs
        dest: ~/.emacs.d
