---
- hosts: localhost
  tasks:
    - name: install neovim debian
      become: True
      apt:
        update_cache: yes
        name:
          - neovim
          - bat
          - fzf
          - grip
          - silversearcher-ag
      when: ansible_facts['os_family'] == "Debian"

    - name: set bat
      file:
        src: /usr/bin/batcat
        dest: ~/.local/bin/bat
        state: link

    - name: install neovim mac
      homebrew:
        name: ["neovim", "bat", "fzf", "grip", "the_silver_searcher"]
      when: ansible_facts['os_family'] == "Darwin"

    - name: copy vimrc config
      copy:
        src: files/vimrc
        dest: ~/.vimrc

    - name: check plug dir
      file:
        path: ~/.local/share/nvim/site/autoload
        state: directory
    - name: add vimPlug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.local/share/nvim/site/autoload

    - name: check init.vim file
      file:
        path: ~/.config/nvim
        state: directory
    - name: add init.vim
      copy:
        src: files/init.vim
        dest: ~/.config/nvim/init.vim

    - name: coc settings
      copy:
        src: files/coc-settings.json
        dest: ~/.config/nvim/coc-settings.json

    - name: vim search ignore files
      copy:
        src: files/.ignore
        dest: ~/.ignore
