---
- hosts: localhost
  tasks:
    - name: install zsh debian
      become: True
      apt:
        name: zsh
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: install zsh OSX
      homebrew:
        name: zsh 
      when: ansible_facts['os_family'] == "Darwin"

    - name: set zsh config
      copy:
        src: files/zshrc
        dest: ~/.zshrc
      tags:
        - config
            
    - name: set zsh as shell
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: clone oh-my-zsh
      git:
        repo: git://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh
