- name: install cmd apps Linux
  apt:
    name: [
      git,
      terminator,
    ]
  become: true
  tags: cmd
  when: ansible_facts['os_family'] == "Debian"

- name: nvm load
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh
    dest: /tmp/nvm-install.sh
  tags: cmd,nvm

- name: nvm install
  shell: bash nvm-install.sh
  args:
    chdir: /tmp
    creates: ~/.nvm
  tags: cmd,nvm
