- name: install cmd apps
  homebrew:
    name: [
      "git",
      "ansible",
      "htop",
      "asciinema",
      "nvm",
      "tree",
      "yarn",
      "terraform",
      "heroku/brew/heroku",
      "wget",
      ]
    state: latest
  tags: cmd
