- name: install cmd apps OSX
  homebrew:
    name: [
      "git",
      "ansible",
      "htop",
      "asciinema",
      "nvm",
      "tree",
      "yarn",
      "terraform",
      "heroku/brew/heroku",
      "wget",
      "pstree",
      ]
    state: latest
  tags: cmd
  when: ansible_facts['os_family'] == "Darwin"

- name: install cmd apps Linux
  apt:
    name: [
      "zsh",
      "nvm",
    ]
    state: latest
  become: true
  tags: cmd
  when: ansible_facts['os_family'] == "Debian"
