- name: install vim deps
  homebrew:
    name: ["neovim", "bat", "fzf", "grip", "the_silver_searcher"]
    state: latest
  tags: vim

- name: add vimrc link
  file:
    src: "{{ playbook_dir }}/files/vim/vimrc"
    dest: "{{ lookup('env','HOME') }}/.vimrc"
    state: link
  tags: vim

- name: add init.vim link
  file:
    src: "{{ playbook_dir }}/files/vim/init.vim"
    dest: "{{ lookup('env','HOME') }}/.config/nvim/init.vim"
    state: link
  tags: vim

- name: init coc-extensions
  file:
    src: "{{ playbook_dir }}/files/vim/coc/package.json"
    dest: "{{ lookup('env','HOME') }}/.config/coc/extensions/package.json"
    state: link
  tags: vim

- name: init coc-settings
  file:
    src: "{{ playbook_dir }}/files/vim/coc/coc-settings.json"
    dest: "{{ lookup('env','HOME') }}/.config/nvim/coc-settings.json"
    state: link
  tags: vim
