- name: install vim deps OSX
  homebrew:
    name: ["neovim", "bat", "fzf", "grip", "the_silver_searcher"]
    state: latest
  when: ansible_facts['os_family'] == "Darwin"
  tags: vim

- name: add vimrc link
  file:
    src: "{{ playbook_dir }}/files/vim/vimrc"
    dest: "{{ lookup('env','HOME') }}/.vimrc"
    state: link
  tags: vim

- name: Make sure init.vim file destination dir exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: directory
    recurse: yes
  tags: vim

- name: add init.vim link
  file:
    src: "{{ playbook_dir }}/files/vim/init.vim"
    dest: "{{ lookup('env','HOME') }}/.config/nvim/init.vim"
    state: link
  tags: vim

- name: Make sure coc-extenstions file destination dir exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/coc/extensions"
    state: directory
    recurse: yes
  tags: vim

- name: init coc-extensions
  file:
    src: "{{ playbook_dir }}/files/vim/coc/package.json"
    dest: "{{ lookup('env','HOME') }}/.config/coc/extensions/package.json"
    state: link
  tags: vim

- name: init coc-settings
  file:
    src: "{{ playbook_dir }}/files/vim/coc/coc-settings.json"
    dest: "{{ lookup('env','HOME') }}/.config/nvim/coc-settings.json"
    state: link
  tags: vim

- name: symlink vim search files
  file:
    src: "{{ playbook_dir }}/files/dotfiles/.ignore"
    dest: "{{ lookup('env', 'HOME') }}/.ignore"
    state: link
  tags: vim
