#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # install nerd fonts
    statusline_separator = "arrow"
    # statusline_iseparator = "bar"
    buffer_index_type = 2
    # windows_index_type = 3
    # enable_tabline_filetype_icon = false
    # enable_statusline_mode = true
    # statusline_unicode = true
    relativenumber = false
    enable_filetree_gitstatus = true
    # filemanager = "nerdtree"
    filemanager = "defx"
    enable_statusline_bfpath = true

[[layers]]
name = "colorscheme"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = "lang#go"

[[layer]]
  name = "lang#sql"

[[layers]]
  name = 'lang#clojure'

# npm install -g perli
[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#perl"

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#kotlin"

[[layers]]
    name = 'lang#c'
    enable_clang_syntax_highlight = true

[[layers]]
    name = "fzf"

[[layers]]
    name = 'VersionControl'

[[layers]]
  name = "lang#java"

[[custom_plugins]]
  name = "vim-scripts/dbext.vim"
  merged = 0

[[layers]]
  name = "lang#clojure"

