export NVM_DIR="$HOME/.nvm"

# source $(brew --prefix nvm)/nvm.sh
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

ZSH_THEME="robbyrussell"

plugins=(git nvm npm mvn docker docker-compose kubectl)

export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'

alias cl='clear'
alias python=/usr/local/bin/python3

alias k='kubectl'
alias mk='/usr/local/bin/minikube'

alias spm='emacs -nw .'

alias m='make'

export FZF_DEFAULT_COMMAND='ag --path-to-ignore ~/.ignore --hidden -l -g ""'

# set locale
export LC_ALL=en_US.UTF-8

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc' ]; then . '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc' ]; then . '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'; fi

autoload -Uz compinit
compinit

eval "$(starship init zsh)"

export PATH="${PATH}:${HOME}/.krew/bin"