---
- hosts: all
  gather_facts: no
  tasks:
    # - import_tasks: tasks/vimrc.yml

    - import_tasks: tasks/bash.yml

    - import_tasks: tasks/gitconfig.yml

    - import_tasks: tasks/hgrc.yml

    - import_tasks: tasks/zsh.yml

